import type { StrapiTeamMember } from "@/lib/strapi";

/**
 * Fallback team members with local photos and LinkedIn URLs.
 * Used when Strapi CMS data is unavailable or incomplete.
 */
export const fallbackTeamMembers: StrapiTeamMember[] = [
  {
    id: 1,
    documentId: "benjamin-ziza",
    firstName: "Benjamin",
    lastName: "Ziza",
    role: "Co-founder & CFO",
    slug: "benjamin-ziza",
    photo: { url: "/images/team/benjamin-ziza.jpg" } as any,
    linkedIn: "https://www.linkedin.com/in/benjamin-ziza/",
    order: 1,
    showInHero: true,
  },
  {
    id: 2,
    documentId: "deisy-arias-ramirez",
    firstName: "Deisy",
    lastName: "Arias Ramirez",
    role: "Fractional CFO",
    slug: "deisy-arias-ramirez",
    photo: { url: "/images/team/deisy-arias-ramirez.jpg" } as any,
    linkedIn: "https://www.linkedin.com/in/deisy-arias-ramirez/",
    order: 2,
    showInHero: false,
  },
  {
    id: 3,
    documentId: "florent-greth",
    firstName: "Florent",
    lastName: "Greth",
    role: "Fractional CFO",
    slug: "florent-greth",
    photo: { url: "/images/team/florent-greth.jpg" } as any,
    linkedIn: "https://www.linkedin.com/in/florent-greth/",
    order: 3,
    showInHero: false,
  },
  {
    id: 4,
    documentId: "guillaume-rostand",
    firstName: "Guillaume",
    lastName: "Rostand",
    role: "Founding Partner & CMO",
    slug: "guillaume-rostand",
    photo: { url: "/images/team/guillaume-rostand.jpg" } as any,
    linkedIn: "https://www.linkedin.com/in/guillaumerostand/",
    order: 4,
    showInHero: false,
  },
  {
    id: 5,
    documentId: "sebastien-doat",
    firstName: "Sébastien",
    lastName: "Doat",
    role: "Co-fondateur et CFO",
    slug: "sebastien-doat",
    photo: null,
    linkedIn: "https://www.linkedin.com/in/sebastien-doat-fractional-cfo/",
    order: 5,
    showInHero: false,
  },
  {
    id: 6,
    documentId: "ornella-salgado",
    firstName: "Ornella",
    lastName: "Salgado",
    role: "Analyste financière",
    slug: "ornella-salgado",
    photo: null,
    linkedIn: "https://www.linkedin.com/in/ornellaslgd/",
    order: 6,
    showInHero: false,
  },
  {
    id: 7,
    documentId: "tom-jaufre",
    firstName: "Tom",
    lastName: "Jaufre",
    role: "Finance CFO",
    slug: "tom-jaufre",
    photo: null,
    linkedIn: "https://www.linkedin.com/in/tom-jaufre-65904175/",
    order: 7,
    showInHero: false,
  },
  {
    id: 8,
    documentId: "pauline-mathieu",
    firstName: "Pauline",
    lastName: "Mathieu",
    role: "Analyste financière",
    slug: "pauline-mathieu",
    photo: null,
    linkedIn: "https://www.linkedin.com/in/pauline-mathieu-082488160/",
    order: 8,
    showInHero: false,
  },
];
